### ISSUE TITLE
Fix nav bar for mobile devices

### ISSUE THREAD

**Issue by TheSoumenMondal** [titouan-joseph/upptime#293]
**Describe the bug**
The navbar is overflowing the mobile screen size.

**Screenshots**
![image](https://github.com/user-attachments/assets/ee568304-0759-41ca-a6a3-b2f08e2094be)

**Comment by TheSoumenMondal** [comment]
I would like to work on this issue .

**Comment by titouan-joseph** [comment]
Please use the original project for this 

https://github.com/upptime/upptime

Thank you
